services:
  database:
    image: postgres:16-alpine
    container_name: db
    restart: unless-stopped
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - app-network

  server:
    build: .
    container_name: server
    restart: always
    depends_on:
      - database
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./uploads:/usr/src/app/uploads
    networks:
      - app-network

networks:
  app-network:

volumes:
  pg: